namespace AsgaSistemas.saga.CE.OiLegal.BusinessEntities.Domain.Resultado.NonoDigito
{
    public class ChamadaNonoDigito
    {
        public string FormatoOrig { get; set; }
        public string Bilhetador { get; set; }
        public string UfBilhetador { get; set; }
        public string CategoriaBilhetador { get; set; }
        public string TipoCdr { get; set; }
        public string NumA { get; set; }
        public string NumAOriginal { get; set; }
        public string NumFisicoA { get; set; }
        public string IndNumFisicoOrigA { get; set; }
        public string NumPtsA { get; set; }
        public string NaiA { get; set; }
        public string EotA { get; set; }
        public string EotDoadoraA { get; set; }
        public string CnlA { get; set; }
        public string AreaLocalA { get; set; }
        public string UfA { get; set; }
        public string AreaTarifariaA { get; set; }
        public string TipoTerminalA { get; set; }
        public string FlagTipoA { get; set; }
        public string IndRuralA { get; set; }
        public string IndPortabilidadeA { get; set; }
        public string FlagEmpA { get; set; }
        public string FlagRoamingA { get; set; }
        public string CategoriaAssinanteA { get; set; }
        public string CategoriaEfetivaA { get; set; }
        public string IndTldnA { get; set; }
        public string NumB { get; set; }
        public string NumBOriginal { get; set; }
        public string NumFisicoB { get; set; }
        public string IndNumFisicoOrigB { get; set; }
        public string NumPtsB { get; set; }
        public string NumRedeB { get; set; }
        public string NaiB { get; set; }
        public string EotB { get; set; }
        public string EotDoadoraB { get; set; }
        public string CnlB { get; set; }
        public string AreaLocalB { get; set; }
        public string UfB { get; set; }
        public string AreaTarifariaB { get; set; }
        public string TipoTerminalB { get; set; }
        public string FlagTipoB { get; set; }
        public string IndRuralB { get; set; }
        public string IndPortabilidadeB { get; set; }
        public string FlagEmpB { get; set; }
        public string IndTldnB { get; set; }
        public string NumC { get; set; }
        public string NumCOriginal { get; set; }
        public string NumFisicoC { get; set; }
        public string IndNumFisicoOrigC { get; set; }
        public string EotC { get; set; }
        public string EotDoadoraC { get; set; }
        public string CnlC { get; set; }
        public string AreaLocalC { get; set; }
        public string UfC { get; set; }
        public string AreaTarifariaC { get; set; }
        public string TipoTerminalC { get; set; }
        public string FlagTipoC { get; set; }
        public string IndRuralC { get; set; }
        public string IndPortabilidadeC { get; set; }
        public string FlagEmpC { get; set; }
        public string IndTldnC { get; set; }
        public string ParteTarifada { get; set; }
        public string ParteTarifadaEfetiva { get; set; }
        public string FimSelecao { get; set; }
        public string FimSelecaoEfetivo { get; set; }
        public string DataHoraLocal { get; set; }
        public string DataHoraBilhetada { get; set; }
        public string DuracaoOriginal { get; set; }
        public string Duracao { get; set; }
        public string CausaSaida { get; set; }
        public string ContadorParciais { get; set; }
        public string RotaEntrada { get; set; }
        public string EmpresaOrigRotaEntrada { get; set; }
        public string EmpresaDestRotaEntrada { get; set; }
        public string IndEmpresaRotaEntrada { get; set; }
        public string IndItxRotaEntrada { get; set; }
        public string UfRotaEntrada { get; set; }
        public string IndTarifacaoRotaEntrada { get; set; }
        public string CnRotaEntrada { get; set; }
        public string AreaLocalRotaEntrada { get; set; }
        public string FlagTipoRotaEntrada { get; set; }
        public string JuntorEntrada { get; set; }
        public string RotaSaida { get; set; }
        public string EmpresaOrigRotaSaida { get; set; }
        public string EmpresaDestRotaSaida { get; set; }
        public string IndEmpresaRotaSaida { get; set; }
        public string IndItxRotaSaida { get; set; }
        public string UfRotaSaida { get; set; }
        public string IndTarifacaoRotaSaida { get; set; }
        public string CnRotaSaida { get; set; }
        public string AreaLocalRotaSaida { get; set; }
        public string FlagTipoRotaSaida { get; set; }
        public string JuntorSaida { get; set; }
        public string Opc { get; set; }
        public string Dpc { get; set; }
        public string Circuito { get; set; }
        public string ClasseChamada { get; set; }
        public string ClasseChamadaEfetiva { get; set; }
        public string IndDesvio { get; set; }
        public string IndAtendimento { get; set; }
        public string IndRedeInteligente { get; set; }
        public string IndVpn { get; set; }
        public string FlagServicos { get; set; }
        public string IndFalhaSeqMensagens { get; set; }
        public string IndFluxoChamada { get; set; }
        public string InfoTranslacaoA { get; set; }
        public string InfoTranslacaoB { get; set; }
        public string InfoTranslacaoC { get; set; }
        public string EstadoChamada { get; set; }
        public string CspRi { get; set; }
        public string IndAssinanteRi { get; set; }
        public string CodCritica { get; set; }
        public string FlagFreeService { get; set; }
        public string FlagCenarioChamada1Perna { get; set; }
        public string FlagCenarioChamada2Perna { get; set; }
        public string FlagClassificacao { get; set; }
        public string FlagDownstream { get; set; }
        public string IndPortabilidadeGlobal { get; set; }
        public string TextoConsulta102 { get; set; }
        public string Flag9DigitoA { get; set; }
        public string Flag9DigitoB { get; set; }
        public string Flag9DigitoC { get; set; }
        public string AssinanteAPortabilidadeTab { get; set; }
        public string CodDddAssinanteA { get; set; }
        public string CodDddAssinanteB { get; set; }
        public string CodEmpresaAssinanteA { get; set; }
        public string CodEmpresaAssinanteB { get; set; }

    }
}
